### ISSUE TITLE
Framework does not compiles for Python 3.7.3

### ISSUE THREAD

**Issue by didix21** [gumob/TLDExtractSwift#7]
**Platform**
    - iOS 11
    - macOS Catalina 10.15.6
    - Swift 5.2.5
    - Python 3.7.3
    - XCode 11.6

When running `carthage update --platform iOS` fails when it's trying to compile TLDExtract package. The following error is displayed.

``` bash
Traceback (most recent call last):
  File "update-psl.py", line 18, in <module>
    response = urlopen(psl_url)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 548, in _open
    'unknown_open', req)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1387, in unknown_open
    raise URLError('unknown url type: %s' % type)
urllib.error.URLError: <urlopen error unknown url type: https>
Command PhaseScriptExecution failed with a nonzero exit code

** ARCHIVE FAILED **


The following build commands failed:
	PhaseScriptExecution Update\ Public\ Suffix\ List /Users/didaccoll/Library/Caches/org.carthage.CarthageKit/DerivedData/11.6_11E708/TLDExtractSwift/2.1.0/Build/Intermediates.noindex/ArchiveIntermediates/TLDExtract-macOS/IntermediateBuildFilesPath/TLDExtract.build/Release/TLDExtract-macOS.build/Script-A7A0ED63219EC891004FBE05.sh
```

If I run carthage with python 2.7.18 works fine. Seems that python 3.7.3 is not supported.

**Comment by didix21** [comment]
After doing some research I found it's a problem how python is installed and seems that my system mac's python does not has installed ssl support. I solved the problem using [pyenv](https://github.com/pyenv/pyenv) and installing it throught it. Thus I can close the issue.
